services:
  - type: web
    name: forcastapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/test_app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
