name: Deploy Streamlit App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create required directories
      run: |
        mkdir -p app/static
        mkdir -p app/data
        
    - name: Set file permissions
      run: |
        chmod -R 755 app/
        
    - name: Test Streamlit
      run: |
        streamlit run app/test_app.py &
        sleep 5
        curl http://localhost:8501/healthz

    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_APP_URL: https://forcastapp.streamlit.app
      run: |
        echo "Deployment is handled by Streamlit Cloud directly from the repository"
